import { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Download, Loader2, Sparkles, Wand2, QrCode as LucideQrCode, Upload, Image as ImageIcon, Link, Mail, Phone, MessageSquare, Type, Wifi } from 'lucide-react';
import { GoogleGenAI } from '@google/genai';
import { generateArtisticQRCode } from '../lib/qr-generator';

export function GeneratorView() {
  const [mode, setMode] = useState<'ai' | 'upload'>('ai');
  const [dataType, setDataType] = useState<'url' | 'email' | 'phone' | 'sms' | 'text' | 'wifi'>('url');
  
  // Data State
  const [targetUrl, setTargetUrl] = useState(`${window.location.origin}${window.location.pathname}?scan=true`);
  const [emailTo, setEmailTo] = useState('');
  const [emailSubject, setEmailSubject] = useState('');
  const [emailBody, setEmailBody] = useState('');
  const [phoneNumber, setPhoneNumber] = useState('');
  const [smsMessage, setSmsMessage] = useState('');
  const [plainText, setPlainText] = useState('');
  const [wifiSsid, setWifiSsid] = useState('');
  const [wifiPassword, setWifiPassword] = useState('');
  const [wifiEncryption, setWifiEncryption] = useState<'WPA' | 'WEP' | 'nopass'>('WPA');
  const [wifiHidden, setWifiHidden] = useState(false);

  // Styling options
  const [qrStyle, setQrStyle] = useState<'dark' | 'neon' | 'cyber' | 'matrix' | 'synthwave'>('dark');
  const [dotShape, setDotShape] = useState<'rounded' | 'square' | 'circle' | 'diamond'>('rounded');
  const [finderShape, setFinderShape] = useState<'square' | 'rounded' | 'circle'>('square');

  // Input States
  const [prompt, setPrompt] = useState('A glowing cyberpunk cityscape, neon lights, highly detailed, 4k');
  const [uploadedImage, setUploadedImage] = useState<string | null>(null);
  
  // Caches for instant theme tweaking
  const [cachedAiImage, setCachedAiImage] = useState<string | null>(null);
  const [cachedPrompt, setCachedPrompt] = useState<string>('');

  const [isGenerating, setIsGenerating] = useState(false);
  const [resultImage, setResultImage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => {
      if (event.target?.result) {
        setUploadedImage(event.target.result as string);
      }
    };
    reader.readAsDataURL(file);
  };

  const handleGenerate = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    
    // Silent escape validation fix
    if (dataType === 'url' && !targetUrl.trim()) return;

    setIsGenerating(true);
    setError(null);
    setResultImage(null);

    try {
      let payloadUrl = '';
      if (dataType === 'url') {
        if (!targetUrl.trim()) throw new Error('Please enter a target URL.');
        payloadUrl = targetUrl;
      } else if (dataType === 'email') {
        payloadUrl = `mailto:${emailTo}?subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`;
      } else if (dataType === 'phone') {
        payloadUrl = `tel:${phoneNumber}`;
      } else if (dataType === 'sms') {
        payloadUrl = `sms:${phoneNumber}?body=${encodeURIComponent(smsMessage)}`;
      } else if (dataType === 'text') {
        payloadUrl = plainText;
      } else if (dataType === 'wifi') {
        payloadUrl = `WIFI:T:${wifiEncryption};S:${wifiSsid};P:${wifiPassword};H:${wifiHidden ? 'true' : 'false'};;`;
      }
      
      let baseImageUrl = '';

      if (mode === 'ai') {
        if (!prompt.trim()) throw new Error('Please enter a prompt.');
        
        if (cachedAiImage && prompt === cachedPrompt) {
          baseImageUrl = cachedAiImage;
        } else {
          const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
          const response = await ai.models.generateContent({
            model: 'gemini-3.1-flash-image-preview',
            contents: {
              parts: [{ text: `A beautiful clean design: ${prompt}. High contrast, vibrant colors.` }],
            },
            config: {
              imageConfig: {
                aspectRatio: "1:1",
                imageSize: "1K"
              }
            }
          });

          let base64EncodeString = '';
          if (response.candidates && response.candidates[0].content.parts) {
            for (const part of response.candidates[0].content.parts) {
              if (part.inlineData) {
                base64EncodeString = part.inlineData.data;
                break;
              }
            }
          }

          if (!base64EncodeString) {
            throw new Error('No image was generated by the AI.');
          }

          baseImageUrl = `data:image/png;base64,${base64EncodeString}`;
        }
      } else {
        if (!uploadedImage) throw new Error('Please upload an image first.');
        baseImageUrl = uploadedImage;
      }

      const combinedQrDataUrl = await generateArtisticQRCode(payloadUrl, baseImageUrl, qrStyle, dotShape, finderShape);
      
      setResultImage(combinedQrDataUrl);
      if (mode === 'ai') {
         setCachedAiImage(baseImageUrl);
         setCachedPrompt(prompt);
      }
    } catch (err: any) {
      console.error("Generation error", err);
      if (err.message?.includes('API key not valid')) {
         setError('API key is invalid. Please ensure you selected a valid Cloud Project.');
      } else {
         setError(err.message || 'An error occurred while generating the QR code.');
      }
    } finally {
      setIsGenerating(false);
    }
  }

  const handleDownload = () => {
    if (!resultImage) return;
    const a = document.createElement('a');
    a.href = resultImage;
    a.download = `zenai-qr-${Date.now()}.png`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="min-h-screen bg-[#0D0D0D] text-white font-sans flex flex-col selection:bg-[#EAFF00]/30 select-none overflow-x-hidden">
      
      {/* Background decoration from theme */}
      <div className="absolute top-0 right-0 w-[50%] h-[50%] bg-gradient-to-bl from-[#EAFF00]/10 to-transparent pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[30%] h-[30%] bg-gradient-to-tr from-[#EAFF00]/5 to-transparent pointer-events-none" />

      <div className="max-w-[1400px] mx-auto w-full p-6 md:p-10 flex flex-col flex-1 h-full z-10 relative">
        <header className="flex flex-col md:flex-row justify-between md:items-start mb-10 border-b border-white/10 pb-8 gap-6 md:gap-0">
          <div className="flex flex-col">
            <div className="flex items-center gap-3 mb-2">
              <div className="w-4 h-4 bg-[#EAFF00] rounded-full shadow-[0_0_15px_#EAFF00]"></div>
              <span className="text-[10px] font-mono tracking-[0.4em] text-[#EAFF00] uppercase">Nano Banana Pro v2.0</span>
            </div>
            <h1 className="text-4xl md:text-6xl font-black tracking-tighter leading-none italic uppercase">
              Artistic <span className="text-[#EAFF00] stroke-black stroke-1">Engine</span>
            </h1>
          </div>
          <div className="flex gap-8 text-left md:text-right">
            <div>
              <p className="text-[9px] uppercase opacity-40 font-mono tracking-widest mb-1">Processing Unit</p>
              <p className="text-xs font-mono">B-22X Neural Core</p>
            </div>
            <div>
              <p className="text-[9px] uppercase opacity-40 font-mono tracking-widest mb-1">Current Load</p>
              <p className="text-xs font-mono text-[#EAFF00]">0.012ms Latency</p>
            </div>
          </div>
        </header>

        <main className="flex-1 flex flex-col md:grid md:grid-cols-12 gap-10">
          <div className="col-span-12 md:col-span-4 flex flex-col gap-8 order-2 md:order-1">
            <div className="flex bg-white/5 border border-white/10 rounded-xl overflow-hidden p-1">
              <button
                onClick={() => setMode('ai')}
                className={`flex-1 py-3 text-xs font-mono font-bold uppercase rounded-lg flex items-center justify-center gap-2 transition-all ${mode === 'ai' ? 'bg-[#EAFF00] text-black shadow-lg' : 'text-white/60 hover:text-white hover:bg-white/5'}`}
              >
                <Wand2 className="w-4 h-4" /> AI Generate
              </button>
              <button
                onClick={() => setMode('upload')}
                className={`flex-1 py-3 text-xs font-mono font-bold uppercase rounded-lg flex items-center justify-center gap-2 transition-all ${mode === 'upload' ? 'bg-[#EAFF00] text-black shadow-lg' : 'text-white/60 hover:text-white hover:bg-white/5'}`}
              >
                <Upload className="w-4 h-4" /> Upload
              </button>
            </div>

            <form onSubmit={handleGenerate} className="flex flex-col h-full gap-8">
              
              {mode === 'ai' ? (
                <div className="group relative bg-white/5 border border-white/10 p-6 rounded-2xl flex-shrink-0 transition-colors focus-within:border-white/30 focus-within:bg-white/10">
                  <label className="absolute -top-3 left-6 px-2 bg-[#0D0D0D] text-[10px] font-mono text-[#EAFF00] uppercase tracking-widest">Artistic Prompt</label>
                  <textarea
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    placeholder="e.g. A lush magical forest with glowing mushrooms..."
                    className="w-full bg-transparent border-none text-sm leading-relaxed text-white/90 italic placeholder-white/30 focus:outline-none focus:ring-0 min-h-[100px] resize-none"
                    disabled={isGenerating}
                  />
                </div>
              ) : (
                <div className="group relative bg-white/5 border border-white/10 p-6 rounded-2xl flex-shrink-0 transition-colors focus-within:border-white/30 focus-within:bg-white/10 flex flex-col items-center justify-center">
                  <label className="absolute -top-3 left-6 px-2 bg-[#0D0D0D] text-[10px] font-mono text-[#EAFF00] uppercase tracking-widest">Upload Image</label>
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleFileUpload}
                    ref={fileInputRef}
                    className="hidden"
                  />
                  {uploadedImage ? (
                    <div className="relative w-full h-[140px] rounded-xl overflow-hidden group/image border border-white/20">
                      <img src={uploadedImage} alt="Uploaded" className="w-full h-full object-cover" />
                      <div className="absolute inset-0 bg-black/60 opacity-0 group-hover/image:opacity-100 transition-opacity flex items-center justify-center">
                        <button type="button" onClick={() => fileInputRef.current?.click()} className="px-4 py-2 border border-white/30 bg-black/50 backdrop-blur-md rounded-lg text-xs font-mono uppercase text-white hover:bg-white/10">
                          Replace Image
                        </button>
                      </div>
                    </div>
                  ) : (
                    <button
                      type="button"
                      onClick={() => fileInputRef.current?.click()}
                      className="w-full h-[140px] border-2 border-dashed border-white/20 rounded-xl flex flex-col items-center justify-center gap-3 hover:border-[#EAFF00]/50 hover:bg-[#EAFF00]/5 transition-all text-white/60 hover:text-[#EAFF00]"
                    >
                      <ImageIcon className="w-8 h-8" />
                      <span className="text-xs font-mono uppercase tracking-wider">Click to Upload</span>
                    </button>
                  )}
                </div>
              )}


              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-[11px] uppercase tracking-[0.2em] font-bold text-white/60">Style Matrix</span>
                  <span className="text-[10px] font-mono text-[#EAFF00]">AI_HYPER_DRIVE</span>
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <div className="p-3 bg-[#EAFF00] text-black text-[11px] font-black uppercase text-center rounded-lg cursor-default">Nano Base</div>
                  <div className="p-3 bg-white/5 border border-white/10 text-[11px] font-black uppercase text-center rounded-lg opacity-50 cursor-default">Oil Canvas</div>
                  <div className="p-3 bg-white/5 border border-white/10 text-[11px] font-black uppercase text-center rounded-lg opacity-50 cursor-default">Voxelized</div>
                  <div className="p-3 bg-white/5 border border-white/10 text-[11px] font-black uppercase text-center rounded-lg opacity-50 cursor-default">Sketch-v2</div>
                </div>
              </div>

              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-[11px] uppercase tracking-[0.2em] font-bold text-white/60">QR Theme</span>
                </div>
                <div className="grid grid-cols-3 gap-2">
                  <button type="button" onClick={() => setQrStyle('dark')} className={`p-3 text-[11px] font-black uppercase text-center rounded-lg transition-colors ${qrStyle === 'dark' ? 'bg-[#EAFF00] text-black shadow-lg' : 'bg-white/5 border border-white/10 text-white/60 hover:bg-white/10 hover:text-white'}`}>Dark</button>
                  <button type="button" onClick={() => setQrStyle('neon')} className={`p-3 text-[11px] font-black uppercase text-center rounded-lg transition-colors ${qrStyle === 'neon' ? 'bg-[#EAFF00] text-black shadow-lg' : 'bg-white/5 border border-white/10 text-white/60 hover:bg-white/10 hover:text-white'}`}>Neon</button>
                  <button type="button" onClick={() => setQrStyle('cyber')} className={`p-3 text-[11px] font-black uppercase text-center rounded-lg transition-colors ${qrStyle === 'cyber' ? 'bg-[#EAFF00] text-black shadow-lg' : 'bg-white/5 border border-white/10 text-white/60 hover:bg-white/10 hover:text-white'}`}>Cyber</button>
                </div>
              </div>

              {error && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-red-400 text-sm bg-red-400/10 p-4 rounded-xl border border-red-400/20 font-mono">
                  ERROR: {error}
                </motion.div>
              )}

              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-[11px] uppercase tracking-[0.2em] font-bold text-white/60">Data Source</span>
                  <span className="text-[10px] font-mono text-[#EAFF00]">ENCODE_TARGET</span>
                </div>
                
                <div className="flex bg-white/5 border border-white/10 rounded-xl overflow-x-auto p-1 custom-scrollbar">
                  {[
                    { id: 'url', label: 'URL', icon: Link },
                    { id: 'email', label: 'Email', icon: Mail },
                    { id: 'phone', label: 'Phone', icon: Phone },
                    { id: 'sms', label: 'SMS', icon: MessageSquare },
                    { id: 'text', label: 'Text', icon: Type },
                    { id: 'wifi', label: 'WiFi', icon: Wifi }
                  ].map((tab) => (
                    <button
                      key={tab.id}
                      type="button"
                      onClick={() => setDataType(tab.id as any)}
                      className={`flex-1 py-3 px-4 text-[10px] font-mono font-bold uppercase rounded-lg flex flex-col items-center justify-center gap-1 transition-all min-w-[70px] ${dataType === tab.id ? 'bg-white/10 text-[#EAFF00] shadow-lg border border-white/10' : 'text-white/40 hover:text-white hover:bg-white/5 border border-transparent'}`}
                    >
                      <tab.icon className="w-4 h-4 mb-1" />
                      {tab.label}
                    </button>
                  ))}
                </div>

                <div className="p-4 bg-white/5 rounded-xl border border-dashed border-white/20 focus-within:border-white/50 focus-within:bg-white/10 transition-colors relative flex flex-col gap-3 min-h-[100px] justify-center">
                  {dataType === 'url' && (
                    <>
                      <label className="absolute -top-3 left-4 px-2 bg-[#0D0D0D] text-[10px] uppercase font-mono text-[#EAFF00] tracking-widest">Website URL</label>
                      <input type="url" value={targetUrl} onChange={(e) => setTargetUrl(e.target.value)} className="w-full bg-transparent border-none text-xs font-mono text-white/90 placeholder-white/30 focus:outline-none focus:ring-0 break-all" placeholder="https://..." required />
                    </>
                  )}
                  {dataType === 'email' && (
                    <>
                      <label className="absolute -top-3 left-4 px-2 bg-[#0D0D0D] text-[10px] uppercase font-mono text-[#EAFF00] tracking-widest">Email Address</label>
                      <input type="email" value={emailTo} onChange={(e) => setEmailTo(e.target.value)} className="w-full bg-transparent border-b border-white/10 pb-2 text-xs font-mono text-white/90 placeholder-white/30 focus:outline-none focus:ring-0 focus:border-[#EAFF00]/50" placeholder="hello@example.com" required />
                      <input type="text" value={emailSubject} onChange={(e) => setEmailSubject(e.target.value)} className="w-full bg-transparent border-b border-white/10 pb-2 text-xs font-mono text-white/90 placeholder-white/30 focus:outline-none focus:ring-0 focus:border-[#EAFF00]/50" placeholder="Subject" />
                      <textarea value={emailBody} onChange={(e) => setEmailBody(e.target.value)} className="w-full bg-transparent border-none text-xs font-mono text-white/90 placeholder-white/30 focus:outline-none focus:ring-0 min-h-[40px] resize-none" placeholder="Message body..." />
                    </>
                  )}
                  {dataType === 'phone' && (
                    <>
                      <label className="absolute -top-3 left-4 px-2 bg-[#0D0D0D] text-[10px] uppercase font-mono text-[#EAFF00] tracking-widest">Phone Number</label>
                      <input type="tel" value={phoneNumber} onChange={(e) => setPhoneNumber(e.target.value)} className="w-full bg-transparent border-none text-xs font-mono text-white/90 placeholder-white/30 focus:outline-none focus:ring-0 break-all" placeholder="+1 234 567 8900" required />
                    </>
                  )}
                  {dataType === 'sms' && (
                    <>
                      <label className="absolute -top-3 left-4 px-2 bg-[#0D0D0D] text-[10px] uppercase font-mono text-[#EAFF00] tracking-widest">Send SMS</label>
                      <input type="tel" value={phoneNumber} onChange={(e) => setPhoneNumber(e.target.value)} className="w-full bg-transparent border-b border-white/10 pb-2 text-xs font-mono text-white/90 placeholder-white/30 focus:outline-none focus:ring-0 focus:border-[#EAFF00]/50" placeholder="+1 234 567 8900" required />
                      <textarea value={smsMessage} onChange={(e) => setSmsMessage(e.target.value)} className="w-full bg-transparent border-none text-xs font-mono text-white/90 placeholder-white/30 focus:outline-none focus:ring-0 min-h-[40px] resize-none" placeholder="Text message..." />
                    </>
                  )}
                  {dataType === 'text' && (
                    <>
                      <label className="absolute -top-3 left-4 px-2 bg-[#0D0D0D] text-[10px] uppercase font-mono text-[#EAFF00] tracking-widest">Plain Text</label>
                      <textarea value={plainText} onChange={(e) => setPlainText(e.target.value)} className="w-full bg-transparent border-none text-xs font-mono text-white/90 placeholder-white/30 focus:outline-none focus:ring-0 min-h-[80px] resize-none" placeholder="Enter any text here..." required />
                    </>
                  )}
                  {dataType === 'wifi' && (
                    <>
                      <label className="absolute -top-3 left-4 px-2 bg-[#0D0D0D] text-[10px] uppercase font-mono text-[#EAFF00] tracking-widest">WiFi Network</label>
                      <input type="text" value={wifiSsid} onChange={(e) => setWifiSsid(e.target.value)} className="w-full bg-transparent border-b border-white/10 pb-2 text-xs font-mono text-white/90 placeholder-white/30 focus:outline-none focus:ring-0 focus:border-[#EAFF00]/50" placeholder="Network Name (SSID)" required />
                      <input type="password" value={wifiPassword} onChange={(e) => setWifiPassword(e.target.value)} className="w-full bg-transparent border-b border-white/10 pb-2 text-xs font-mono text-white/90 placeholder-white/30 focus:outline-none focus:ring-0 focus:border-[#EAFF00]/50" placeholder="Password" />
                      <div className="flex items-center gap-4 pt-2">
                        <select value={wifiEncryption} onChange={(e) => setWifiEncryption(e.target.value as any)} className="bg-white/5 border border-white/10 rounded px-2 py-1 text-xs font-mono text-white/90 focus:outline-none focus:border-[#EAFF00]/50">
                          <option value="WPA">WPA/WPA2</option>
                          <option value="WEP">WEP</option>
                          <option value="nopass">None</option>
                        </select>
                        <label className="flex items-center gap-2 text-xs font-mono text-white/60 cursor-pointer">
                          <input type="checkbox" checked={wifiHidden} onChange={(e) => setWifiHidden(e.target.checked)} className="accent-[#EAFF00]" />
                          Hidden Network
                        </label>
                      </div>
                    </>
                  )}
                </div>
              </div>

              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-[11px] uppercase tracking-[0.2em] font-bold text-white/60">Design Controls</span>
                </div>
                
                <div className="flex flex-col gap-3">
                  <div className="bg-white/5 border border-white/10 rounded-xl p-4">
                    <span className="text-[9px] uppercase tracking-widest text-[#EAFF00] mb-3 block">Color Theme</span>
                    <div className="flex flex-wrap gap-2">
                      {['dark', 'neon', 'cyber', 'matrix', 'synthwave'].map(style => (
                        <button key={style} type="button" onClick={() => setQrStyle(style as any)} className={`px-3 py-2 text-[10px] uppercase font-bold rounded-lg transition-all ${qrStyle === style ? 'bg-[#EAFF00] text-black shadow-lg' : 'bg-black/50 text-white/60 hover:text-white border border-white/5 hover:border-white/20'}`}>
                          {style}
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="bg-white/5 border border-white/10 rounded-xl p-4">
                    <span className="text-[9px] uppercase tracking-widest text-[#EAFF00] mb-3 block">Pattern Shape</span>
                    <div className="flex flex-wrap gap-2">
                      {['rounded', 'square', 'circle', 'diamond'].map(shape => (
                        <button key={shape} type="button" onClick={() => setDotShape(shape as any)} className={`px-3 py-2 text-[10px] uppercase font-bold rounded-lg transition-all ${dotShape === shape ? 'bg-[#EAFF00] text-black shadow-lg' : 'bg-black/50 text-white/60 hover:text-white border border-white/5 hover:border-white/20'}`}>
                          {shape}
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="bg-white/5 border border-white/10 rounded-xl p-4">
                    <span className="text-[9px] uppercase tracking-widest text-[#EAFF00] mb-3 block">Marker Shape</span>
                    <div className="flex flex-wrap gap-2">
                      {['square', 'rounded', 'circle'].map(shape => (
                        <button key={shape} type="button" onClick={() => setFinderShape(shape as any)} className={`px-3 py-2 text-[10px] uppercase font-bold rounded-lg transition-all ${finderShape === shape ? 'bg-[#EAFF00] text-black shadow-lg' : 'bg-black/50 text-white/60 hover:text-white border border-white/5 hover:border-white/20'}`}>
                          {shape}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-auto flex flex-col gap-4 pt-4">
                <button
                  type="submit"
                  disabled={isGenerating || (mode === 'ai' && !prompt.trim()) || (mode === 'upload' && !uploadedImage) || (dataType === 'url' && !targetUrl.trim())}
                  className="w-full py-5 bg-[#EAFF00] text-black font-black uppercase tracking-[0.2em] text-sm rounded-xl hover:shadow-[0_0_40px_rgba(234,255,0,0.3)] transition-all disabled:opacity-50 disabled:hover:shadow-none flex items-center justify-center gap-3"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      Synthesizing...
                    </>
                  ) : (
                    "Generate Masterpiece Code"
                  )}
                </button>
              </div>
            </form>
          </div>

          <div className="col-span-12 md:col-span-8 flex flex-col items-center justify-center bg-white/[0.03] rounded-3xl border border-white/10 relative overflow-hidden min-h-[500px] order-1 md:order-2">
            <div className="absolute top-0 left-0 w-full h-full opacity-10 bg-[radial-gradient(#EAFF00_1px,transparent_1px)] [background-size:20px_20px]"></div>
            
            <div className="relative z-10 w-full flex items-center justify-center p-4 md:p-8">
              <AnimatePresence mode="wait">
                {isGenerating ? (
                  <motion.div
                    key="loading"
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.9 }}
                    className="p-8 bg-black rounded-[40px] shadow-2xl border border-[#EAFF00]/30 shadow-[0_0_50px_rgba(234,255,0,0.1)]"
                  >
                    <div className="relative w-[300px] h-[300px] md:w-[400px] md:h-[400px] rounded-3xl overflow-hidden flex flex-col items-center justify-center">
                      <div className="absolute inset-0 bg-gradient-to-tr from-[#EAFF00] to-orange-500 opacity-20 animate-pulse"></div>
                      <Loader2 className="w-16 h-16 text-[#EAFF00] animate-spin relative z-10 mb-6" />
                      <p className="text-[#EAFF00] font-mono tracking-widest text-sm uppercase relative z-10">Neural Rendering...</p>
                    </div>
                  </motion.div>
                ) : resultImage ? (
                  <motion.div
                    key="result"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="flex flex-col items-center gap-8 w-full max-w-[500px]"
                  >
                    <div className="p-4 md:p-6 bg-black rounded-[40px] shadow-2xl border border-white/20 relative group w-full">
                      <div className="relative rounded-3xl overflow-hidden group border border-white/10">
                        <img src={resultImage} alt="Generated QR" className="w-[300px] h-[300px] md:w-[450px] md:h-[450px] object-cover mx-auto" />
                        
                        <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center backdrop-blur-sm">
                          <button
                            onClick={handleDownload}
                            className="px-8 py-4 bg-[#EAFF00] text-black font-black uppercase tracking-widest text-sm rounded-xl flex items-center gap-3 transform translate-y-4 group-hover:translate-y-0 transition-all duration-300 shadow-[0_0_20px_rgba(234,255,0,0.5)]"
                          >
                            <Download className="w-5 h-5" /> Download
                          </button>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                ) : (
                  <motion.div
                    key="placeholder"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="p-8 bg-black rounded-[40px] shadow-2xl border border-white/20"
                  >
                    <div className="relative w-[300px] h-[300px] md:w-[400px] md:h-[400px] rounded-3xl overflow-hidden group border border-white/5 flex flex-col items-center justify-center bg-[#0D0D0D]">
                      <div className="absolute inset-0 bg-gradient-to-tr from-[#EAFF00] to-orange-500 opacity-5"></div>
                      <div className="w-20 h-20 bg-white/5 border border-white/10 rounded-2xl flex items-center justify-center mb-6 text-white/20 group-hover:text-[#EAFF00]/50 transition-colors">
                        <LucideQrCode className="w-10 h-10" />
                      </div>
                      <p className="text-[10px] font-mono text-white/30 uppercase tracking-[0.3em]">Awaiting Input Signal</p>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
            
            {resultImage && (
              <div className="absolute bottom-6 w-full text-center z-20 px-4">
                <div className="inline-flex items-center justify-center gap-3 bg-black/80 backdrop-blur-md px-6 py-3 rounded-full border border-[#EAFF00]/30 shadow-lg text-[#EAFF00]">
                  <LucideQrCode className="w-4 h-4" /> 
                  <span className="text-xs font-mono uppercase tracking-widest">System Ready • Code scannable</span>
                </div>
              </div>
            )}
          </div>
        </main>

        <footer className="mt-8 flex flex-col md:flex-row justify-between items-center md:items-end border-t border-white/5 pt-6 gap-4 md:gap-0">
          <div className="text-[10px] font-mono text-white/20 tracking-tighter text-center md:text-left">
            ID: BF-882-BANANA-PRO-X2 // ENCRYPTION: AES-256-GCM
          </div>
          <div className="flex items-center gap-6">
            <div className="w-32 h-[2px] bg-white/10 relative overflow-hidden hidden md:block">
              <div className="absolute top-0 left-0 h-full w-1/2 bg-[#EAFF00] shadow-[0_0_8px_#EAFF00]"></div>
            </div>
            <span className="text-[11px] font-bold uppercase tracking-widest">Status: <span className="text-[#EAFF00]">Operational</span></span>
          </div>
        </footer>
      </div>
    </div>
  );
}
